run:
  deadline: 10m

linters:
  disable:
  - typecheck
  - structcheck
  enable:
  - golint

issues:
  exclude-rules:
    - path: 'cmd/az-analyze'
      linters:
        - forbidigo
    - path: 'cmd/az-log'
      linters:
        - forbidigo
