name: MacOS Build & Unit Test
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
        id: go

      - name: Build Test
        run: |
          make azuredisk-darwin
      - name: Run unit tests on MacOS
        run: go test -v -race ./pkg/...
