name: Linux Build & Unit Tests V2
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        check-latest: true
      id: go

    - name: Build Test
      env:
        BUILD_V2: true
      run: make azuredisk

    - name: Run Linux Unit Tests
      run: |
        go test -covermode=count -coverprofile=profile.cov -tags azurediskv2 ./pkg/azuredisk
        go test -covermode=count -coverprofile=profile.cov -tags azurediskv2 ./pkg/azdiskschedulerextender

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
