name: Trivy vulnerability scanner
on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
  - cron: "0 13 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
        id: go

      - name: Build an image from Dockerfile
        run: |
          export PUBLISH=true
          export REGISTRY=test
          export IMAGE_VERSION=latest
          export DOCKER_CLI_EXPERIMENTAL=enabled
          make container
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test/azuredisk-csi:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

