name: Windows Build & Unit Tests V2
on:
    pull_request: {}
    push: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
        id: go
      - name: Build Test
        env:
          BUILD_V2: true
        run: |
          make azuredisk-windows
      - name: Run Windows Unit Tests
        run: |
          go test -v -race -tags azurediskv2 ./pkg/azuredisk --use-csi-proxy=false
          go test -v -race -tags azurediskv2 ./pkg/mounter --use-csi-proxy=false
          go test -v -race -tags azurediskv2 ./pkg/provisioner --use-csi-proxy=false
          go test -v -race -tags azurediskv2 ./pkg/azdiskschedulerextender
